### ISSUE TITLE
Related Papers: VideoChat, POPE, X-LLM, KOSMOS-1

### ISSUE THREAD

**Issue by ChenDelong1999** [HenryHZY/Awesome-Multimodal-LLM#1]
Great repo! Here are some complementary related works on Multimodal LLM

- POPE: Polling-based Object Probing Evaluation for Object Hallucination (2023.05.17)
  - https://github.com/RUCAIBox/POPE
  - https://arxiv.org/abs/2305.10355
 
- VideoChat: Chat-Centric Video Understanding (2023.05.10)
  - https://github.com/OpenGVLab/Ask-Anything
  - https://arxiv.org/abs/2305.06355

- X-LLM: Bootstrapping Advanced Large Language Models by Treating Multi-Modalities as Foreign Languages (2023.05.09)
  - https://arxiv.org/abs/2305.04160

- Language Is Not All You Need: Aligning Perception with Language Models (2023.02)
  - https://arxiv.org/abs/2302.14045

**Comment by HenryHZY** [comment]
@ChenDelong1999 Thx for the update. I will check it later.

By the way, I think it is a really good idea to collect some evaluation-related paper for LLM-guided multimodal learning. For example, POPE and MultiInstruct.

**Comment by HenryHZY** [comment]
Updated, feel free to pull request by the way.
