### ISSUE TITLE
Suggest a multimodal dataset

### ISSUE THREAD

**Issue by repo-atvc** [HenryHZY/Awesome-Multimodal-LLM#2]
Thanks for the curated list of multimodal LLM. We have a related work that we hope is added to this awesome repository.

Accountable Textual-Visual Chat Learns to Reject Human Instructions in Image Re-creation (https://arxiv.org/pdf/2303.05983.pdf)

Project Page: https://matrix-alpha.github.io/

**Comment by HenryHZY** [comment]
Thx, I will check it later.
